name: ecscrape
dependencies:
  - python==3.12
  - aiohttp
  - cartopy
  - cfgrib
  - eccodes
  - healpy>=1.16.3
  - numcodecs
  - numpy
  - requests
  - scipy
  - xarray
  - pip
  - pip:
    - aiohttp_retry
    - easygems
    - gribscan
