name: ecscrape
dependencies:
  - python==3.12
  - aiohttp
  - cartopy
  - cfgrib
  - dask
  - eccodes
  - fsspec
  - healpy>=1.16.3
  - numcodecs
  - numpy
  - requests
  - requests-toolbelt
  - scipy
  - xarray
  - zarr
  - pip
  - pip:
    - aiohttp_retry
    - easygems
    - gribscan>=0.0.12
